/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author T1G Pro
 */
public class TampilanKbm extends javax.swing.JFrame {

public Connection conn;
public Statement cn;
    /**
     * Creates new form TampilanKbm
     */
    public TampilanKbm() {
        initComponents();
//        this.setLocationRelativeTo(null);
tampilkan();
    }
  public void sambung (){
        try{
            
           conn = DriverManager.getConnection("jdbc:mysql://localhost/raraaquatik","root","");
          
        } catch (SQLException e) {
            System.err.println(""+e);
        }
    }
   private void tampilkan(){
    try{
        Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/raraaquatik","root","");
        ResultSet rs = cn.createStatement().executeQuery("select * from datasiswa"
            );
    }catch (SQLException ex) {
        
    }
    
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtjam = new javax.swing.JTextField();
        txtsts = new javax.swing.JTextField();
        txtcari = new javax.swing.JTextField();
        jbuton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));
        setMinimumSize(new java.awt.Dimension(700, 520));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(51, 255, 255));
        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel4.setText("KODE SISWA");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(170, 50, 260, 87);

        jLabel5.setBackground(new java.awt.Color(51, 255, 255));
        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel5.setText("NAMA SISWA");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(170, 170, 250, 80);

        jLabel6.setBackground(new java.awt.Color(51, 255, 255));
        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel6.setText("JAM KEHADIRAN");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(160, 300, 300, 80);

        jLabel8.setBackground(new java.awt.Color(51, 255, 255));
        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel8.setText("STATUS");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(170, 420, 270, 73);

        txtnama.setBackground(new java.awt.Color(153, 255, 255));
        txtnama.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jPanel1.add(txtnama);
        txtnama.setBounds(420, 180, 230, 81);

        txtjam.setBackground(new java.awt.Color(153, 255, 255));
        txtjam.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jPanel1.add(txtjam);
        txtjam.setBounds(420, 300, 230, 76);

        txtsts.setBackground(new java.awt.Color(153, 255, 255));
        txtsts.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jPanel1.add(txtsts);
        txtsts.setBounds(420, 420, 230, 73);

        txtcari.setBackground(new java.awt.Color(153, 255, 255));
        txtcari.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jPanel1.add(txtcari);
        txtcari.setBounds(420, 50, 160, 90);

        jbuton.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jbuton.setText("CARI");
        jbuton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbutonMouseClicked(evt);
            }
        });
        jPanel1.add(jbuton);
        jbuton.setBounds(580, 50, 70, 90);

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(50, 50, 80, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-40, -40, 740, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbutonMouseClicked
String sql = "select * from datasiswa where kode_siswa = '"+txtcari.getText()+"'";
try{
   Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/raraaquatik","root","");
        ResultSet rs = cn.createStatement().executeQuery(sql);
    if(rs.next()){
        String nm =rs.getString("nama_siswa");
        String nm1 = rs.getString("jmbelajar");
        String nm2 = rs.getString("status");
        txtnama.setText(nm);
        txtjam.setText(nm1);
        txtsts.setText(nm2);
        jbuton.setEnabled(false);
        txtnama.setEnabled(false);
        txtjam.setEnabled(false);
        jbuton.setEnabled(false);
        tampilkan();
        
    }else{
        JOptionPane.showMessageDialog(null, "Koneksi gagal!");
    }
}catch (Exception e){
    System.out.println("dfg" +e);
    
}
    }//GEN-LAST:event_jbutonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         jadwal_kbm kbm;
        kbm = new jadwal_kbm();
        kbm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanKbm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanKbm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanKbm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanKbm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanKbm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbuton;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtjam;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtsts;
    // End of variables declaration//GEN-END:variables
}
